id = "vhs80"
name = "VHS80"
version = "1.0.0"
schema_version = 1
authors = ["Taha YVR <taha@noiserandom.com>"]
description = "A muted retro 80s theme."
repository = "https://github.com/tahayvr/vhs80-zed"
